#name: Test
#
#on: push
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [14.x]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: Install and test
#        run: |
#          npm ci
#          npm run nx affected:test --coverage --base=$BEFORE_SHA
#        env:
#          CI: true
